/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as OddsRouteImport } from './routes/odds'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OddsTodayRouteImport } from './routes/odds.today'
import { Route as OddsPremierLeagueRouteImport } from './routes/odds.premier-league'
import { Route as OddsChampionsLeagueRouteImport } from './routes/odds.champions-league'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const OddsRoute = OddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OddsTodayRoute = OddsTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => OddsRoute,
} as any)
const OddsPremierLeagueRoute = OddsPremierLeagueRouteImport.update({
  id: '/premier-league',
  path: '/premier-league',
  getParentRoute: () => OddsRoute,
} as any)
const OddsChampionsLeagueRoute = OddsChampionsLeagueRouteImport.update({
  id: '/champions-league',
  path: '/champions-league',
  getParentRoute: () => OddsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/fixtures': typeof FixturesRoute
  '/odds': typeof OddsRouteWithChildren
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/odds/champions-league': typeof OddsChampionsLeagueRoute
  '/odds/premier-league': typeof OddsPremierLeagueRoute
  '/odds/today': typeof OddsTodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/fixtures': typeof FixturesRoute
  '/odds': typeof OddsRouteWithChildren
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/odds/champions-league': typeof OddsChampionsLeagueRoute
  '/odds/premier-league': typeof OddsPremierLeagueRoute
  '/odds/today': typeof OddsTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/fixtures': typeof FixturesRoute
  '/odds': typeof OddsRouteWithChildren
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/odds/champions-league': typeof OddsChampionsLeagueRoute
  '/odds/premier-league': typeof OddsPremierLeagueRoute
  '/odds/today': typeof OddsTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/fixtures'
    | '/odds'
    | '/predictions'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/vip'
    | '/odds/champions-league'
    | '/odds/premier-league'
    | '/odds/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/fixtures'
    | '/odds'
    | '/predictions'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/vip'
    | '/odds/champions-league'
    | '/odds/premier-league'
    | '/odds/today'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/fixtures'
    | '/odds'
    | '/predictions'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/vip'
    | '/odds/champions-league'
    | '/odds/premier-league'
    | '/odds/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FixturesRoute: typeof FixturesRoute
  OddsRoute: typeof OddsRouteWithChildren
  PredictionsRoute: typeof PredictionsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  VipRoute: typeof VipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odds': {
      id: '/odds'
      path: '/odds'
      fullPath: '/odds'
      preLoaderRoute: typeof OddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odds/today': {
      id: '/odds/today'
      path: '/today'
      fullPath: '/odds/today'
      preLoaderRoute: typeof OddsTodayRouteImport
      parentRoute: typeof OddsRoute
    }
    '/odds/premier-league': {
      id: '/odds/premier-league'
      path: '/premier-league'
      fullPath: '/odds/premier-league'
      preLoaderRoute: typeof OddsPremierLeagueRouteImport
      parentRoute: typeof OddsRoute
    }
    '/odds/champions-league': {
      id: '/odds/champions-league'
      path: '/champions-league'
      fullPath: '/odds/champions-league'
      preLoaderRoute: typeof OddsChampionsLeagueRouteImport
      parentRoute: typeof OddsRoute
    }
  }
}

interface OddsRouteChildren {
  OddsChampionsLeagueRoute: typeof OddsChampionsLeagueRoute
  OddsPremierLeagueRoute: typeof OddsPremierLeagueRoute
  OddsTodayRoute: typeof OddsTodayRoute
}

const OddsRouteChildren: OddsRouteChildren = {
  OddsChampionsLeagueRoute: OddsChampionsLeagueRoute,
  OddsPremierLeagueRoute: OddsPremierLeagueRoute,
  OddsTodayRoute: OddsTodayRoute,
}

const OddsRouteWithChildren = OddsRoute._addFileChildren(OddsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FixturesRoute: FixturesRoute,
  OddsRoute: OddsRouteWithChildren,
  PredictionsRoute: PredictionsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  VipRoute: VipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
